open-feature/open-feature-operator

Makefile, README.md
Signed-off-by: James-Milligan <james@omnant.co.uk>
- add the `make deploy-operator` command to manage the deployment of the operator / cert manager.
The existing command sequence did not include any waits and as a result on a fresh cluster it was possible to provision the `end-to-end.yaml` without the webhook running, resulting in the flagd sidecar nto being injected into the pod. I created a makefile command called `make deploy-operator` which handles these awaits and creates the namespace.
- adds this new feature
https://github.com/open-feature/open-feature-operator/issues/103
This issue is related, however it does not completely fulfill any of the criterea, as further work is requried.
1.  Create a local cluster with MicroK8s or Kind (forward requests from your localhost:30000 to your …
=> feat: makefile deploy-operator

.github/workflows/pr-checks.yml, .github/workflows/pr-lint.yml, .github/workflows/release-please.yml
Signed-off-by: Eddie Knight <knight@linux.com>
Adds permissions to the github actions workflows based on recommendations by CLOMonitor and OpenSSF scorecard.
Part of #139 
Contributing this based on discussion with @justinabrahms as part of the CNCF Security Slam
=> chore: Updated workflow permissions for CLOMonitor status

.github/workflows/release-please.yml
Sign the image using [cosign](https://docs.sigstore.dev/cosign/overview/) when making releases.
=> chore: Sign the container in the repo

README.md
Removes namespace argument from e2e example in readme
Fixes #201
=> chore: remove namespace argument from e2e example in readme

config/manager/kustomization.yaml
Reverts kustomization image name change.
=> chore: revert kustomization image name change

test/e2e/simple-flag-evaluation.sh
Signed-off-by: James Milligan <james@omnant.co.uk>
- check response within the reply loop, resolves a race condition found in the `002.crd-configuration-reconciliation` test
https://github.com/open-feature/open-feature-operator/issues/263
=> test: resolve race condition in e2e tests

chart/templates/rendered.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, main.go, webhooks/pod_webhook.go
=> feat: introduce configurable resource limits for flagd sidecar

README.md
For more information, please see the following issue.
https://github.com/badges/shields/issues/8671
=> chore: update build badge to new format

docs/getting_started.md
Improves the getting started guide of the documentation.
- removes a typo
- moves the annotations in the example to the correct place
- updates outputs for flagd v0.2.7
After installing the open-feature-operator locally in minikube I ran into issues with the instructions in the getting started documentation. I figured out the issues and thought it could be useful to update the docs. :)
=> docs: improve getting started guide

Makefile, docs/getting_started.md
=> feat: upgrade flagd to v0.3.0

docs/getting_started.md, renovate.json
Configures renovate to use a regex manager to monitor the FLAGD_VERSION in Makefile.
Fixes #291 
Tested that this works in my forked repo: https://github.com/skyerus/open-feature-operator/pull/63/files
=> chore: renovate regex manager to monitor FLAGD_VERSION in Makefile

apis/core/v1alpha1/featureflagconfiguration_types.go, apis/core/v1alpha1/flagsourceconfiguration_types.go, apis/core/v1alpha2/flagsourceconfiguration_types.go, controllers/featureflagconfiguration_controller.go, webhooks/featureflagconfiguration_webhook_test.go, webhooks/pod_webhook.go, webhooks/pod_webhook_test.go, webhooks/suite_test.go
We need to mount dirs, not files, so our previous solution to handle multiple configmaps didn't work (events weren't being seen in flagd).
This change mounts each ff/configmap in it's own unique dir, preserving all events and allowing multiples.
=> fix: mount dirs not files

Makefile, apis/core/v1alpha1/flagsourceconfiguration_types.go
Sets defaultTag to `INPUT_FLAGD_VERSION`, this fixes `make update-flagd`.
=> fix: set defaultTag to INPUT_FLAGD_VERSION

test/e2e/flag-evaluation.sh, test/e2e/tests/001.flagd-response.sh, test/e2e/tests/003.configmap-configuration-reconciliation.sh
Introduces e2e test coverage of filepath sync provider config update reconciliation.
Fixes #333
=> chore: test filepath sync config change is reconciliated

apis/core/v1alpha1/flagsourceconfiguration_types.go, apis/core/v1alpha2/flagsourceconfiguration_conversion.go, apis/core/v1alpha2/flagsourceconfiguration_types.go, chart/open-feature-operator/README.md, chart/open-feature-operator/templates/rendered.yaml, chart/open-feature-operator/values.yaml, config/crd/bases/core.openfeature.dev_flagsourceconfigurations.yaml, config/overlays/helm/manager.yaml, docs/feature_flag_configuration.md, webhooks/pod_webhook_test.go
- adds a new `sidecarConfiguration.logFormat` helm value that is handed over to the operator as an env var
- sets the default sidecar log format to json both in code and in the CRD itself, as well as the helm chart
Fixes #334
=> feat: add log format configuration options through helm chart

Makefile
- Upgrades ENVTEST_K8S_VERSION to 1.26.1
Locally, using this version reduces test instability (it still fails but less frequently).
=> chore: upgrade ENVTEST_K8S_VERSION to 1.26.1

.github/workflows/pr-checks.yml, .github/workflows/release-please.yml, Dockerfile
- optimizes container builds by moving the reading of build arguments to right before they are needed
- with the next `RUN` command after an `ARG` command, the docker layer cache is always invalidated, since the RUN command can have different effects with different build args that the image builder cannot foresee.
- by moving the build arg steps further down in the dockerfile, caching should be improved by a lot
- I also enabled github actions caching for the docker builds to improve pipeline times
=> chore: improve container build layer caching

renovate.json
- removes ignored renovate paths
Renovate must update some e2e test assertions when flagd is updated.
=> chore: remove ignored renovate paths

config/rbac/flagd_kubernetes_sync_clusterrolebinding.yaml
- removes OF namespace prefix from clusterrolebindings -> this way kustomize kicks in and adds the prefix to the the resources
=> fix: remove unneeded OF namespace prefix from clusterrolebindings

webhooks/pod_webhook.go
- fixed bug caused by using old prefix from flagd-proxy provider config
=> fix: removed old prefix from flagd-proxy provider config

docs/getting_started.md
- replaces instructions for running `make deploy-demo` with a link to the [cloud-native-demo](https://github.com/open-feature/cloud-native-demo).
=> docs: replace `make deploy-demo` command with a link to the `cloud-native-demo` repo

controllers/common/flagd-injector.go, controllers/common/flagd-injector_test.go
This PR fixes the flagd proxy sync provider address by removing the `grpc://` prefix from the URL pointing to the flagd proxy service. This is required because otherwise the flagd sidecar will run into the following error:
```
2023-04-25T09:09:27.611Z	fatal	cmd/start.go:180	rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address grpc://flagd-proxy-svc.open-feature-operator-system.svc.cluster.local:8015: too many colons in address"	{"component": "start"}
```
=> fix: remove 'grpc://' prefix from proxy sync address

webhooks/pod_webhook.go, webhooks/pod_webhook_test.go
Follow-up from the discussion https://github.com/open-feature/open-feature-operator/pull/497#discussion_r1259387714
- the `RoleBinding` that attaches elevated permissions to the `ServiceAccount` of a Pod is created iff there is a K8s provider
=> chore: adapt ServiceAccount only in case of K8s Provider

.github/workflows/pr-checks.yml
- Add kind node image matrix for end to end testing
Following the discussion here: https://github.com/open-feature/open-feature-operator/issues/500
=> ci: add kind node image matrix for end to end testing

webhooks/pod_webhook.go
Fix issue with admission webhook on older k8s version
Fixes #500
We then can say open-feature-operator is working on k8s >= 1.22
I tested on kind with a 1.22 image (`image: kindest/node:v1.22.9`) .
```shell
kind create cluster --config ./test/e2e/kind-cluster.yml
kind load docker-image local-image-tag:latest
IMG=local-image-tag:latest make deploy-operator
IMG=local-image-tag:latest make e2e-test
```
=> fix: use admission webhook namespace if pod namespace is empty

Makefile, apis/core/v1alpha1/featureflagconfiguration_types_test.go, apis/core/v1alpha1/flagsourceconfiguration_types.go, apis/core/v1alpha1/flagsourceconfiguration_types_test.go, apis/core/v1beta1/featureflag_types.go, apis/core/v1beta1/featureflag_types_test.go, apis/core/v1beta1/featureflagsource_types.go, apis/core/v1beta1/featureflagsource_types_test.go
Part of #531 
Changes made in this PR are coming from the knowledge from [this PR](https://github.com/open-feature/open-feature-operator/pull/539)
=> feat: prepare apis for v1beta1 controllers onboarding

apis/core/v1beta1/featureflagsource_types.go, apis/core/v1beta1/featureflagsource_types_test.go
Part of #517 
Preparation for https://github.com/open-feature/open-feature-operator/pull/550
To restrict the setup of the sidecar image and tag, we need to remove the image and tag parameters from FFS CRD. These values will be read from the env variables of the operator deployment. Also the reading of the env variables should not happen in the CRD struct function, but should be handled in a common place for all env variable, for example in the `main.go`. Please see the [linked PR](https://github.com/open-feature/open-feature-operator/pull/550) for more details
=> chore: adapt API for sidecar image and tag restriction

.github/workflows/release-please.yml, release-please-config.json
Improves CI by,
- ignoring component name in tag (experimental)
- make ci steps dependable on one another
=> chore: ignore component for release tag and make release dependable

.github/workflows/pr-checks.yml, webhooks/pod_webhook.go
Reintroduces using admission webhook namespace if pod namespace is empty
Fixes #500
This was accidentally removed during a recent refactor. It wasn't caught in our tests because the oldest version that's tested is `1.25`. I've added a comment above the change to make it clear why this logic is there.
=> fix: use webhook ns if empty, more test versions

main.go
=> fix: create index for pod annotation path for allowkubernetessync annotation instead of deployment

docs/feature_flag_source.md
- Remove `metricsPort`, was for `v1alpha3`(or before?), replace with `managementPort `
- Remove `image`/`tag`, not present in `v1beta1`
- Add link to the full list.
=> chore: update `FeatureFlagSource` documentation for v1beta1

common/flagdproxy/flagdproxy.go, common/flagdproxy/flagdproxy_test.go
- Remove the usage of the metrics-port flag and and the corresponding tests.
This flag was deprecated and is now removed from flagd so it needs to be removed here before using the new version of flagd.
Closes #586
=> chore: Remove metrics-port flag/usage from flagdproxy startup

apis/core/v1beta1/featureflagsource_types.go, common/flagdinjector/flagdinjector.go, common/flagdinjector/flagdinjector_test.go
This wasn't being passed to the flagd startup.
Relates to: https://github.com/open-feature/open-feature-operator/pull/587
=> fix: flagd mgmt port setting ignored

apis/core/v1beta1/featureflagsource_types.go, apis/core/v1beta1/featureflagsource_types_test.go
Openfeature operator does not support 'interval' for source flag type.
This PR add's the 'interval' as uint32, as per specification to the Source API definition
Once API rebuilt with new API version including the structure change, I will create PR with changes to common/flagdinjector to incorporate this change
btw, first PR here, so be gentle as I dont know the process to get things into the awesome work  you guys have done so far :) 
Signed-off-by: Martin Coetzee <martin@martincoetzee.com>
=> feat: added interval to the openfeature api source

.gitignore, Makefile, chart/open-feature-operator/.gitignore, chart/open-feature-operator/README.md, docs/installation.md
- Alters the `Makefile` to move CustomResourceDefinition templates to the crds directory before packaging the helm chart.
- Alters the `.gitignore` to ignore templates in the `crds` directory.
- Updates and cleans up the CRD installation documentation.
- Enables users to optionally skip installation of the CRDs using the `--skip-crds` flag when performing `helm install`
Fixes #624
```sh
make helm-package
helm template ./chart/open-feature-operator -s "templates/crds/*.yaml" | kubectl -f -
helm install open-feature ./chart/open-feature-operator --skip-crds --create-namespace -n open-feature
```
=> fix: Add capability to skip crd installation during helm install

.github/workflows/pr-checks.yml, .github/workflows/release-please.yml, Dockerfile, Makefile
This PR introduces the use of go workspaces. Before this change, anything that involves a change or addition in the `apis` submodule required this to be split into multiple PRs (one for the api change, then a follow up to adapt the code in the controller/webhook). A similar approach is also used in https://github.com/open-feature/flagd, so I think we could also make use of that here
=> chore: use workspaces to make api changes easier

common/flagdinjector/flagdinjector.go, common/flagdinjector/flagdinjector_test.go, webhooks/common.go, webhooks/pod_webhook.go, webhooks/pod_webhook_test.go
Part-of: #542 
- fixed [small issue](https://github.com/open-feature/open-feature-operator/pull/634/files#diff-edf09fdaf271cf47315a206784c3406e9a895fa16bae1ce11e5c0f4ef79d93d1R73) in flaginjector about adding env variables to all containers (not only flagd sidecar)
- adapt flagdinjector tests to test the changed behavior + simplify them
- polish webhook for future extension with in-process evaluation
=> fix: inject env variables to all pod containers

apis/core/v1beta1/flagd_types.go
This can no longer be optional, we iterate over it.
Also add doc about support for an empty-host rule.
Fixes: https://github.com/open-feature/open-feature-operator/issues/656
=> docs: require hosts, mention host-less rules

apis/core/v1beta1/flagd_types.go, config/crd/bases/core.openfeature.dev_flagds.yaml, controllers/core/flagd/resources/ingress.go, controllers/core/flagd/resources/ingress_test.go, docs/crds.md, test/e2e/chainsaw/flagd-with-ingress-default-paths/00-assert.yaml
The previous default paths don't work well, since flagd evaluation requests look like `.../flagd.evaluation.v1.Service/...`. These new default paths work "out of the box".
=> fix: flagd path defaults

chart/open-feature-operator/README.md, chart/open-feature-operator/values.yaml, common/flagdproxy/flagdproxy.go, common/flagdproxy/flagdproxy_test.go, config/crd/bases/core.openfeature.dev_flagds.yaml, config/overlays/helm/manager.yaml, controllers/core/featureflagsource/controller_test.go, controllers/core/flagd/common/common.go, controllers/core/flagd/config.go, controllers/core/flagd/resources/deployment.go, docs/crds.md, main.go
DISCLAIMER: THIS DOES NOT BUILD AND I DO NOT KNOW WHY.
Tested with `make helm-package` and get this error:
```
Error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- exclude-ns.yaml
- manager.yaml
- exclude-validatingwebhook.yaml
`: MalformedYAMLError: yaml: line 9: did not find expected node content in File: manager.yaml
make: *** [Makefile:157: release-manifests] Error 1
```
=> feat: add image pull secrets

.github/scripts/strip-kustomize-helm.sh, Makefile, chart/open-feature-operator/README.md, chart/open-feature-operator/values.yaml, common/flagdproxy/flagdproxy.go, common/flagdproxy/flagdproxy_test.go, config/overlays/helm/manager.yaml, controllers/core/featureflagsource/controller_test.go, controllers/core/flagd/common/common.go, controllers/core/flagd/config.go, controllers/core/flagd/resources/deployment.go, main.go
The previous iteration of this was ALMOST working, but:
- it didn't support multiple secrets
- it broke if you did a helm upgrade without a imagePullSecret, forcing the user to use `--force`.
I've added a sort of hacky "post-processor" script which allows us to add helm control flow where we otherwise couldn't. After talking with @thisthat I think this is the only solution until kustomize supports helm output.
Again, I tested locally, and ImagePullSecrets (even more than one) are added to both the manager deployment and the deployments we create at runtime.
Fixes: https://github.com/open-feature/open-feature-operator/issues/665
=> fix: handle multiple imagePullSecrets

chart/open-feature-operator/README.md, chart/open-feature-operator/values.yaml, config/overlays/helm/manager.yaml
Add `hostNetwork` and `dnsPolicy` settings to enable compatibility with EKS clusters that have a custom CNI. Without these, the MutatingWebhook that adds the flagd sidecar to pods will not function.
- This provided inspiration for this fix: https://github.com/elastic/cloud-on-k8s/issues/1369
- Another issue with the same problem/fix: https://stackoverflow.com/questions/59801157/aws-eks-k8s-cluster-with-weave-cni-plugin-cannot-have-custom-metrics
- The HashiCorp vault sidecar injector explicitly notes this in its Helm chart values as well: https://github.com/hashicorp/vault-helm/blob/834cd7f85a48179bef83ce48f82aec2128bc6020/values.yaml#L328
This relies on `.github/scripts/strip-kustomize-helm.sh` because boolean values have to be true/false without quotes, so to set `hostNetwork` to true …
=> feat: Add hostNetwork flag.

config/overlays/helm/exclude-webhook-server-container-port.yaml, config/overlays/helm/kustomization.yaml
Delete the default webhook-server port (to avoid duplicate) since we build it from helm
=> fix: remove duplicated port in helm

Makefile
- When running `make helm-package` the install script for Kustomize is broken https://github.com/kubernetes-sigs/kustomize/issues/5562
- Add the recommended fix.
- https://github.com/kubernetes-sigs/kustomize/issues/5562
We should investigate if the install script is truly dead and unsupported now, or if, instead of this fix, we should instead push for the installation script to be repaired.
1. Delete `./bin` (`rm -rf ./bin`) from local clone of open-feature-operator
2. Run `make helm-package`
3. Note error:
`Version v5.4.1 does not exist or is not available for linux/amd64.`
4. Apply this patch
5. Re-run `make helm-package`
6. Note error is now gone.
=> fix: Fix Kustomize installation

config/rbac/role.yaml
Add missing poddisruption budget permissions in manager cluster role
Open feature operator now attempts to list, create, and watch pod disruption budget resources for flagd proxy since it can now configure HA replica for flagd proxy
Fixes #717 
Related to #712 
* update existing ClusterRole configuration to include poddisruptionbudget resource permissions for api group: policy
* manually apply changes to ClusterRole resource, change FlagSource and watch for permission errors. Retry with extra verbs until no reconcile errors were encountered.
=> fix: Add missing poddisruption budget permissions in manager cluster role

.github/workflows/pr-checks.yml
We're running into GHCR throttling issues. Switching to ECR should resolve this issue.
https://github.com/aquasecurity/trivy-action/issues/389#issuecomment-2373539982
=> ci(trivy): fetch vulnerabilities DB from ERC

config/rbac/role.yaml, docs/permissions.md
Openfeature operator controller manager needs to be able to update pod disruption budgets as replica counts can be updated
* add update verb to manager role for pod disruption budgets
#717
After deploying v0.8.1 I noticed these new permissions were not in the role. I think I've missed some required change to get these reconciled in to the role resource.
* double check that this get's reconciled to role when updating versions / installing through helm.
- Install via helm to a cluster 
- include flagdProxyConfiguration.replicaCount=2 in helm configuration in values
- add a flagd-proxy FlagSourceConfiguration
- watch openfeature operator controller manager logs, validate PodDisruptionBudget gets updated to have max 2 pods
=> fix: Add missing poddisruptionbudget update verb

.github/workflows/dco-merge-group.yml, .github/workflows/pr-checks.yml
Add dco workaround to support GitHub merge queues
=> ci: add dco workaround, run tests for merge queues

api/core/v1beta1/common/common.go, api/core/v1beta1/common/common_test.go, internal/common/flagdinjector/flagdinjector.go
Allow to configure GCS buckets.
Tested locally, confirmed that flagd deployment is created and that deployment can pull the data (tested on GKE with Workload identity support enabled)
- adds this new feature
Relates to #758
configured feature source to use gs buckets:
```
spec:
sources:
- interval: 15
provider: gcs
source: gs://my-bucket/test.json
```
=> feat(flagd): add support for GCS

config/samples/end-to-end.yaml
Added missing namespace fixed invalid reference to FeatureFlag in FeatureFlagSource.
Fixes bugs in the sample end-to-end K8S manifest
N/A
N/A
N/A
`kubectl apply -f end-to-end.yaml` now results in successful deployment.
=> fix: end-to-end.yaml

cmd/main.go
Fixes API server warning for empty imagePullSecrets
```
INFO    KubeAPIWarningLogger    spec.template.spec.imagePullSecrets[0].name: invalid empty name ""
```
Previously `FlagdConfiguration.ImagePullSecrets` would be `[""]` when no `--image-pull-secrets` is supplied, this results in a invalid `Deployment` resource when a `Flagd` resource is applied. After this change `FlagdConfiguration.ImagePullSecrets` results in `[]` which ensures the generated `Deployment`s don't throw API server warnings.
=> fix: API server warning for empty imagePullSecrets

docs/quick_start.md
=> docs: Fixed numbering in quick_start.md
