open-feature/open-feature-operator

controllers/featureflagconfiguration_controller.go, pkg/utils/utils.go, webhooks/mutating_admission_webhook.go
=> feat: create configmap if manually deleted

webhooks/pod_webhook.go
Making tag and ImagePullPolicy consts, set ImagePullPolicy to "Always" to prevent caching on nodes for now.
=> Always pull most recent flagd

Makefile, config/manager/manager.yaml, webhooks/pod_webhook.go
This pins the flagd version to the release described in the makefile
=> flag pinning

config/samples/end-to-end.yaml
Adding a targeting field to a demo flag in the end-to-end demo.
=> Add targeting demo

.github/workflows/release.yaml
closes #48 
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
=> feat: added end-to-end manifest to release

.gitignore
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>
=> this stops the accidental commit of flagd_version changes

Makefile
https://github.com/open-feature/open-feature-operator/pull/60
=> Updated the schema

Dockerfile
=> Update schema path in Dockerflie

apis/core/v1alpha1/featureflagconfiguration_types.go, controllers/featureflagconfiguration_controller.go, controllers/suite_test.go, main.go, webhooks/featureflagconfiguration_webhook.go, webhooks/pod_webhook.go
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>
=> flagd customisation

webhooks/pod_webhook.go
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>
=> adds nil pointer check

webhooks/pod_webhook.go
This should have been in #77 not sure what happened, my mistake.
=> fix: updated to read from slice

Dockerfile
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>
=> fix: dockerfile golang version

README.md
=> chore: update link to ofep

.github/workflows/pr-checks.yml, Makefile, controllers/suite_test.go, go.mod, go.sum
Signed-off-by: Skye Gill <gill.skye95@gmail.com>
=> feat: pr github action workflow

Makefile
Signed-off-by: jamesmilligan <james@omnant.co.uk>
=> chore: flagd version bump

README.md
more documentation
Fixes https://github.com/open-feature/open-feature-operator/issues/104
=> chore: document the end to end installation process with more explanation

.github/workflows/release-please.yml
- adds a latest tag to the docker image
I'm not sure if we need both `latest` and `main` tags. I left main there since it was previously defined.
=> chore: add latest tag

.github/workflows/release-please.yml
Generate sboms on release. Part of #139
=> chore: Add sbom generation

README.md
I take responsibility for this direct merge - this is to improve our security score with CLOmonitor
=> chore: artifacthub-badge

README.md
=> feat: license scanner

CODEOWNERS
Signed-off-by: Justin Abrahms <justin@abrah.ms>
=> chore: Add myself to code owners.

CODEOWNERS
=> chore: Add beeme1mr as a code owner

Makefile
Signed-off-by: Justin Abrahms <justin@abrah.ms>
=> chore: Create directory if it doesn't exist.

config/samples/end-to-end.yaml, webhooks/pod_webhook.go
Adding a bit more logging in the webhook and namespacing the demo
=> chore: logging/end-to-end improvement

README.md
Signed-off-by: jamesmilligan <james@omnant.co.uk>
- removed the helm section of readme until linked issue is resolved
https://github.com/open-feature/open-feature-operator/issues/199
=> docs: removed helm instructions whilst bug exists (temp)

.github/workflows/release-please.yml
Bump go version in release-assets workflow.
=> chore: bump go version in release-assets workflow

CONTRIBUTING.md, README.md
Adds how to implement a new crd version to the readme
=> chore: how to implement a new crd version

.github/workflows/release-please.yml
Automates the generation and publishing of charts in the release workflow.
#219
=> chore: automate release of charts

.github/workflows/release-please.yml
Prepends image name to `make helm-package` in release charts workflow
=> chore: fix make helm-package command in release charts workflow

.github/workflows/release-please.yml
Include release tag in helm charts publishing.
=> fix: include release tag in helm charts publishing

Makefile, test/e2e/DEVELOPER.md, test/e2e/run.sh, test/e2e/simple-flag-evaluation.sh, test/e2e/tests/001.flagd-response.sh, test/e2e/tests/002.crd-configuration-reconciliation.sh
Applies changes to CRD and asserts that the changes are reflected in a curl to the nginx reverse proxy to flagd.
Fixes #236
=> chore: added crd configuration reconciliation e2e test

README.md
Added cert-manager installation command to helm charts installation section for clarity.
=> chore: added cert-manager installation command to helm charts installation section

chart/open-feature-operator/Chart.yaml
Signed-off-by: James Milligan <james@omnant.co.uk>
- fixes version in chart
=> fix: fix version in chart

chart/open-feature-operator/Chart.yaml, release-please-config.json
- fixes release please versioning
=> fix: Version fix

Makefile, docs/getting_started.md
- adds new section to the getting started guide to automatically deploy and port forward to the demo application
https://github.com/open-feature/open-feature-operator/issues/106
=> docs: automated demo deployment

apis/core/v1alpha1/featureflagconfiguration_types.go, apis/core/v1alpha1/flagsourceconfiguration_types.go, apis/core/v1alpha2/featureflagconfiguration_conversion.go, apis/core/v1alpha2/flagsourceconfiguration_conversion.go, apis/core/v1alpha2/flagsourceconfiguration_types.go, chart/open-feature-operator/README.md, chart/open-feature-operator/templates/rendered.yaml, chart/open-feature-operator/values.yaml, config/crd/bases/core.openfeature.dev_flagsourceconfigurations.yaml, config/overlays/helm/manager.yaml, webhooks/pod_webhook.go, webhooks/pod_webhook_test.go
- adds configuration for default sync provider 
- extends helm values to provide access to this configuration
https://github.com/open-feature/open-feature-operator/issues/318
=> feat: default sync provider configuration

webhooks/pod_webhook.go
- Fixes `spec.containers[1].volumeMounts[1].mountPath: Invalid value: "/etc/flagd/": must be unique` when using multiple FeatureFlagConfiguration with file syncProvider
Fixes #319 
I've tested this manually. I'm in the process of adding to the e2e tests to cover this scenario, I've uncovered some unexpected behaviour while doing so (bizarre reconciliation). I'm going to investigate further, in the meantime it'd be good to get this fix in. Tests will come after
=> fix: gave configmaps volume mounts a subpath to allow for multiple mounts

apis/core/v1alpha1/featureflagconfiguration_types.go, controllers/featureflagconfiguration_controller.go, webhooks/pod_webhook.go, webhooks/pod_webhook_test.go
Signed-off-by: Skye Gill <gill.skye95@gmail.com>
- Enforces uniqueness of featureflagconfiguration file path across namespaces.
=> fix: uniqueness of featureflagconfiguration file path

.github/workflows/pr-checks.yml, apis/core/v1alpha1/flagsourceconfiguration_types.go
- ensures there is a diff when `make update-flagd` is run against PRs
=> ci: flagd version replace check

test/e2e/e2e.yml, test/e2e/flag-evaluation.sh, test/e2e/tests/001.flagd-response.sh, test/e2e/tests/002.crd-configuration-reconciliation.sh
Signed-off-by: Skye Gill <gill.skye95@gmail.com>
Fixes #324
=> chore: test multiple sync providers

apis/core/v1alpha1/featureflagconfiguration_types.go, webhooks/pod_webhook_test.go
Signed-off-by: James Milligan <james@omnant.co.uk>
- updates file mount path to conform with schema store regex
=> refactor: update file mount path to conform with schema store regex

docs/permissions.md
Follow up of https://github.com/open-feature/open-feature-operator/pull/348
=> docs: Update permissions docs

docs/installation.md
Adds docs for upgrading CRDs via helm.
Fixes: https://github.com/open-feature/open-feature-operator/issues/354
=> chore: document crd upgrades

docs/installation.md
- add AND operator to sequential commands
- fix uninstall via Helm command
=> docs: add AND operator to sequential commands

test/e2e/tests/004.disabled.sh
- Adds new e2e test for openfeature.dev/enabled annotation set to false
=> chore: e2e test for openfeature.dev/enabled annotation set to false

docs/annotations.md, docs/feature_flag_configuration.md, docs/flag_source_configuration.md, docs/getting_started.md, docs/permissions.md
Simply adds better formatting to existing docs and makes minor corrections
=> chore: improve formatting and content

webhooks/pod_webhook.go
makes some refactoring to prepare for kuttl tests implementation
- refactor pod mutator to reduce the complexity of the handler function 
part of #391
=> chore: refactor pod webhook mutator

go.mod, go.sum, webhooks/featureflagconfiguration_webhook.go, webhooks/featureflagconfiguration_webhook_test.go, webhooks/suite_test.go
- migrate webhook ginkgo tests to standard unit tests
- minor refactoring of admission webhook
=> chore: refactor admission webhook tests

README.md
- Adds a link to the Killercoda demo
=> docs: add killercoda demo link

renovate.json
- update renovate config to bump test assert version
=> chore: update flagd renovate detection

config/overlays/helm/manager.yaml, controllers/core/flagsourceconfiguration/controller.go, docs/kube_flagd_proxy.md, renovate.json
- updates env var prefix from `KUBE_PROXY_` to `FLAGD_PROXY_`
=> fix: update flagd proxy env var prefix

Makefile, config/crd/bases/core.openfeature.dev_featureflagconfigurations.yaml, config/crd/bases/core.openfeature.dev_flagsourceconfigurations.yaml, docs/crds.md
- removes flaky content from crd descriptions
Fixes #470
=> ci: escape chars

docs/getting_started.md
- updates crd version in getting started guide
=> docs: update crd version in getting started guide

docs/getting_started.md
=> docs: add advanced flagd links

docs/quick_start.md, docs/troubleshoot.md
Adds a troubleshooting guide with potential issues users can come across.
Added first entry about service accounts and cluster role binding requirements 
related - https://github.com/open-feature/open-feature-operator/issues/500
=> chore: adding troubleshooting guide

apis/core/v1alpha2/featureflagconfiguration_types.go, apis/core/v1beta1/featureflag_types.go
=> chore: adapt shortcuts for custom resources

.github/workflows/release-please.yml
Fixes ci by fixing step dependencies
=> fix: fix build

README.md, config/samples/pod.yaml, docs/README.md, docs/installation.md, docs/quick_start.md, docs/v1beta_migration.md
Improvements for https://github.com/open-feature/open-feature-operator/issues/528 
Adds migration guide where we highlight what was changed and what to change to use the new OFO.
=> chore: migration docs

docs/v1beta_migration.md
Adds helm migration section and add refernce to `FlagSourceConfiguration` renaming
=> chore: add helm migration section

README.md
=> chore: add link to tutorial in README

.github/workflows/golangci-lint.yml
Follow up to #635 
I noticed in another PR with changes to the API that this needed to be adapted still
=> chore: init workspace before linting

renovate.json
Adds renovate coverage for env cfg tags in `envconfig.go`
=> chore: add rule for env cfg tags

README.md
https://openfeature.dev/community/ is a better source of truth
- adds this new feature
Fixes #1234523
=> docs: Replace the old events calendar by the OpenFeature community Page link

config/overlays/helm/mutatingwebhook.yaml
=> fix: namespace for ca injection for mutatingwebhook solving #759
